---
abstract: 'A Least-Recently Used cache'
author:
  - 'Michael G Schwern <schwern@pobox.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Tie-Cache-LRU
no_index:
  directory:
    - t
    - inc
requires:
  Carp::Assert: '0'
  Class::Data::Inheritable: '0'
  Class::Virtual: '0'
  Test::More: '0.82'
  enum: '0'
resources:
  bugtracker: https://github.com/schwern/Tie-Cache-LRU/issues
  repository: https://github.com/schwern/Tie-Cache-LRU
version: '20150301'
